
POST http://localhost:3333/usuarios
Content-Type: application/json


{
  "nome": "Carlos Pereira",
  "email": "carlos@example.com",
  "telefone": "963258741"
}


###

GET http://localhost:3333/usuarios


###
PUT  http://localhost:3333/usuarios



