
POST http://localhost:3333/usuarios
Content-Type: application/json


{
  "nome": "Vitor Pereira",
  "email": "vitor@example.com",
  "telefone": "963264741"
}


###

GET http://localhost:3333/usuarios


###
PUT  http://localhost:3333/usuarios



